Rewrite/post
KaanMol/Krypton pull request #8
Opened 2017-03-08 18:44 UTC by KaanMol

**TO DO**
- [x] Rewrite get controller

- [x] Rewrite post controller

- [x] Rewrite edit controller

- [x] Rewrite delete controller

- [ ] Update controllers if code is not good enough

- [ ] Recheck all controllers for bugs and code mistakes

- [ ] Rewrite to async

2017-03-10 10:11 UTC, nusje2000 requested changes

2023-02-24 23:08 UTC, Somfic commented
seems good to me!

2023-02-24 23:08 UTC, Somfic approved these changes

2024-08-14 15:09 UTC, nusje2000 commented on modules/api/v1/post/controllers/post/read.controller.js
>            res.send([]);
Een 403 zou het beste zijn denk ik, dat is meteen duidelijke feedback naar de gebruiker dat je geen toegang hebt.

2024-08-14 15:11 UTC, closed without merging